name: netinfer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core dependencies
  - python>=3.8
  - pip
  - snakemake>=9.0.0
  - coincbc

  # Python packages for core functionality
  - pandas
  - numpy
  - networkx
  - scipy
  - scikit-learn
  - statsmodels
  - plotly
  - dash
  - jinja2
  - pyyaml
  - tqdm
  - biom-format
  - pyvis

  # R dependencies for SPIEC-EASI, propR, and Spearman
  - r-base>=4.0
  - r-essentials
  - r-spieceasi
  - r-propr
  - bioconductor-preprocesscore
  - r-igraph
  - r-tidyverse
  - r-hmisc      # For Spearman correlation
  - r-reshape2   # For data reshaping in Spearman analysis
  - r-jsonlite   # For JSON handling

  # Julia dependencies for FlashWeave
  - julia>=1.6
  
  # FastSpar dependencies
  - fastspar
  - gsl
  - openblas


  # pip entry
  - pip:
    - "."  # Install the netinfer package